server:
  port: 8090

spring:
  application:
    name: spring-security
  redis:
    host: localhost
    port: 6379
    password: secret_password

jwt:
  expirationTime: 300000
  expirationString: expS
  ### securityCode:
  ### Sets the signing key used to verify any discovered JWS digital signature.
  ### If the specified JWT string is not a JWS (no signature), this key is not used.
  securityCode: ${spring.redis.password}
  ### headerKey:
  ### Customize HTTP header to convey the current sessionId instead of cookies.
  ### In this case, the value would be a JWT string which combines sessionId.
  headerKey: Authorization
  ### sessionKey:
  ### The key of sessionId in JWT string.
  sessionKey: sessionId
  authoritiesKey: authorities

security:
  loginUrl: /app-login
  logoutUrl: /app-logout
  whiteList:
      - ${security.url.login}
      - /auth/login/*
  sessionLimit: 1
